import React, { useState } from "react";
import { ArrowLeft, Bell, Check, ChevronDown, ChevronRight, Filter, Paperclip, Phone, Search, Send, Share2, SlidersHorizontal, Upload, Zap } from "lucide-react";

type Props = { onBack?: () => void };
const G = "#2e7d32";

function Shell({ children, dark=false }: { children: React.ReactNode; dark?: boolean }) {
  return <div className={`mx-auto flex min-h-screen w-full max-w-[375px] flex-col overflow-hidden ${dark ? "bg-[#121212] text-white" : "bg-[#f5f5f5] text-[#212121]"}`}>{children}</div>;
}
function StatusBar({ dark=false }: { dark?: boolean }) {
  return <div className={`flex h-11 items-center justify-between px-6 text-[14px] font-semibold ${dark?"text-white":"text-[#212121]"}`}><span>9:41</span><div className="flex items-center gap-2">▮▮▮ ◉ ▣</div></div>;
}
function Header({title,onBack,right}:{title:string;onBack?:()=>void;right?:React.ReactNode}){return <div className="flex h-14 items-center justify-between px-5"><button onClick={onBack} className="grid size-6 place-items-center" aria-label="Back"><ArrowLeft className="size-6"/></button><h1 className="text-[20px] font-bold">{title}</h1><div className="grid size-6 place-items-center">{right}</div></div>}
function BottomIndicator(){return <div className="flex h-[34px] items-start justify-center pb-2 pt-4"><div className="h-[5px] w-[134px] rounded-full bg-black/15"/></div>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-xl bg-white ${className}`}>{children}</div>}
function SettingRow({label,on}:{label:string;on:boolean}){return <div className="flex items-center justify-between p-4"><span className="text-[14px]">{label}</span><div className={`h-6 w-11 rounded-full p-1 ${on?'bg-[#2e7d32]':'bg-[#ddd]'}`}><div className={`size-4 rounded-full bg-white ${on?'translate-x-5':''}`}/></div></div>}
function SettingNav({label,value}:{label:string;value?:string}){return <div className="flex items-center justify-between p-4"><span className="text-[14px]">{label}</span><span className="text-[12px] text-[#616161]">{value??'›'}</span></div>}

export function GlobalSearch({onBack}:Props){return <Shell><StatusBar/><div className="space-y-4"><div className="flex items-center justify-between px-5"><div className="flex items-center gap-3"><button onClick={onBack}><ArrowLeft/></button><h1 className="text-[28px] font-bold">Search</h1></div><span className="text-[16px] text-[#616161]">Cancel</span></div><div className="px-5"><div className="flex h-12 items-center gap-3 rounded-xl border bg-white px-4"><Search className="size-5 text-[#616161]"/><span className="text-[16px] text-[#616161]">Search by token ID, name...</span></div></div><div className="space-y-3 px-5"><div className="flex items-center justify-between"><span className="font-semibold text-[#616161]">Recent Searches</span><span className="font-semibold text-[#2e7d32]">Clear all</span></div>{['TRD-CHL-0892','Teja Chilli Price'].map(x=><div className="flex items-center gap-3" key={x}><span className="text-[18px]">◷</span><span className="text-[16px]">{x}</span></div>)}</div><div><div className="px-0 text-[14px] font-semibold text-[#616161]">Tokens</div><div className="flex items-center gap-4 bg-white p-5"><div className="size-12 rounded-lg bg-[#2e7d32]"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b>TRD-CHL-089234</b><span className="rounded bg-green-50 px-2 py-1 text-[10px] font-bold text-[#2e7d32]">TOKEN</span><span className="rounded bg-green-50 px-2 py-1 text-[10px] font-bold text-[#4caf50]">LISTED</span></div><div className="text-[13px] text-[#616161]">Chilli (Teja) – Grade A | 120 MT</div></div></div><div className="px-0 text-[14px] font-semibold text-[#616161]">Users</div><div className="flex items-center gap-4 bg-white p-5"><div className="grid size-12 place-items-center rounded-full bg-[#eee] text-[19px] font-semibold text-[#616161]">RK</div><div><div className="flex items-center gap-2"><b>Rajesh Kumar</b><span className="rounded bg-blue-50 px-2 py-1 text-[10px] font-bold text-[#2196f3]">USER</span></div><div className="text-[13px] text-[#616161]">Producer – Guntur</div></div></div><div className="p-5"><div className="flex gap-4"><div className="size-12 rounded-lg bg-[#eee]"/><div className="space-y-2"><div className="h-4 w-44 rounded bg-[#eee]"/><div className="h-3 w-28 rounded bg-[#eee]"/></div></div></div></div><BottomIndicator/></div>}

export function Notifications(){return <Shell><StatusBar/><Header title="Notifications" right={<span className="text-[10px] font-semibold text-[#2e7d32]">Mark all as read</span>}/><div className="px-4"><div className="mb-4 flex gap-2">{['All','Unread','Bills','Payments'].map((x,i)=><span key={x} className={`rounded-full px-4 py-2 text-[12px] font-semibold ${i===0?'bg-[#2e7d32] text-white':'bg-[#eee] text-[#616161]'}`}>{x}</span>)}</div><div className="space-y-3">{['New bid received on LOT-556 for ₹158/kg','Payment credited for Invoice INV-001','QC Report for TRD-001 is ready'].map((x,i)=><div key={x} className="border-b border-[#eee] bg-white p-4"><div className="mb-1 text-[13px] font-semibold">{x}</div><div className="text-[11px] text-[#757575]">{i===0?'Today':'1 day ago'}</div></div>)}</div></div><BottomIndicator/></Shell>}

export function VoiceCall(){return <Shell dark><StatusBar dark/><div className="flex h-14 items-center justify-between px-5"><span><SlidersHorizontal className="size-6"/></span><span className="text-[16px] font-semibold">Voice Call</span><span/></div><div className="flex flex-1 flex-col items-center pt-20"><div className="grid size-[120px] place-items-center rounded-full bg-[#e8f5e9] text-[48px] text-[#616161]">PA</div><div className="mt-5 text-center"><div className="text-[24px] font-bold">Priya Agencies (CA)</div><div className="text-[16px] text-white/60">Commission Agent</div></div><div className="mt-8 text-[16px] text-white/80">Ringing...</div><div className="mt-1">•••</div></div><div className="space-y-8 pb-8"><div className="text-center text-[12px] text-white/50">Virtual number — your number is protected</div><div className="flex justify-between px-10">{[<span key="m">⌁</span>,<Phone key="s"/>,<span key="k">⌨</span>].map((x,i)=><div key={i} className="grid size-[60px] place-items-center rounded-full bg-white/10">{x}</div>)}<div className="grid size-[60px] place-items-center rounded-full bg-[#f44336]">⌕</div></div><div className="flex justify-center"><div className="h-[5px] w-[134px] rounded-full bg-white/30"/></div></div></Shell>}

export function Documents({onBack}:Props){const docs=[['Contract_C-001.pdf','20 Jun 2025 • 1.2 MB','red'],['QC_Report_CHL.pdf','19 Jun 2025 • 850 KB','green'],['Invoice_INV-001.pdf','18 Jun 2025 • 420 KB','blue'],['KYC_PAN.jpg','15 Jun 2025 • 2.1 MB','orange']];return <Shell><StatusBar/><Header title="Documents" onBack={onBack} right={<div className="flex gap-4"><Filter/><SlidersHorizontal/></div>}/><div className="flex gap-2 px-5 py-2">{['All','Contracts','Invoices'].map((x,i)=><span key={x} className={`rounded-full px-4 py-2 text-[14px] font-semibold ${i===0?'bg-[#2e7d32] text-white':'bg-[#eee] text-[#616161]'}`}>{x}</span>)}</div><div className="grid grid-cols-2 gap-4 p-4">{docs.map(d=><Card key={d[0]} className="p-3 shadow-[0_4px_6px_rgba(0,0,0,.03)]"><div className="flex justify-between"><div className={`grid size-8 place-items-center rounded-md ${d[2]==='red'?'bg-red-50':d[2]==='green'?'bg-green-50':d[2]==='blue'?'bg-blue-50':'bg-orange-50'}`}>▤</div><div className="flex gap-2 text-[#616161]"><span>⇩</span><Share2 className="size-5"/></div></div><div className="mt-3 truncate text-[14px] font-semibold">{d[0]}</div><div className="text-[11px] text-[#616161]">{d[1]}</div></Card>)}</div><button className="fixed bottom-24 right-5 grid size-14 place-items-center rounded-full bg-[#2e7d32] text-white shadow-lg"><span className="text-3xl">+</span></button><BottomIndicator/></Shell>}

export function QRScanner(){return <Shell dark><StatusBar dark/><Header title="Scan QR Code" right={<Zap className="text-white"/>}/><div className="flex flex-1 flex-col items-center justify-center gap-10"><div className="grid size-[260px] place-items-center rounded-[32px] border-4 border-dashed border-white"><div className="h-0.5 w-[220px] bg-[#2e7d32]"/></div><div className="text-center text-[16px] text-white/80">Align QR code within frame</div></div><div className="rounded-t-[24px] bg-white px-5 pb-10 pt-6"><div className="flex justify-center gap-3 text-[#2e7d32]"><span>▤</span><b>Enter code manually</b></div><p className="mt-4 text-center text-[14px] text-[#616161]">Scan the QR code printed on the token sheet or listed in your dashboard.</p><div className="mt-5 rounded-[16px] border border-[#2e7d32] bg-[#e8f5e9] p-4"><div className="text-[10px] font-bold text-[#2e7d32]">TOKEN QR DETECTED</div><div className="text-[20px] font-bold">TRD-CHL-089234</div><div className="text-[14px] text-[#616161]">Teja Chilli – Grade A</div><div className="mt-3 flex gap-3"><button className="flex-1 rounded-xl bg-[#2e7d32] py-3 font-bold text-white">View Details</button><button className="w-14 rounded-xl border bg-white">↻</button></div></div><div className="flex justify-center pt-8"><div className="h-[5px] w-[134px] rounded-full bg-black/15"/></div></div></Shell>}

export function SupportTicket({onBack}:Props){const [submitted,setSubmitted]=useState(false);return <Shell><StatusBar/><Header title="Support Ticket" onBack={onBack}/><div className="space-y-5 p-5"><Card className="space-y-5 p-5"><label className="block"><div className="mb-2 text-[10px] font-bold text-[#616161]">ISSUE TYPE</div><div className="flex h-12 items-center justify-between rounded-xl border bg-[#f5f5f5] px-4">Technical Issue<ChevronDown/></div></label><label className="block"><div className="mb-2 text-[10px] font-bold text-[#616161]">SUBJECT</div><div className="flex h-12 items-center rounded-xl border bg-white px-4 text-[#9e9e9e]">Brief description...</div></label><label className="block"><div className="mb-2 text-[10px] font-bold text-[#616161]">DESCRIPTION</div><div className="h-24 rounded-xl border bg-white p-4 text-[#9e9e9e]">Describe your issue in detail...</div></label><div><div className="mb-3 text-[10px] font-bold text-[#616161]">ATTACHMENTS</div><div className="flex flex-col items-center justify-center rounded-xl border border-dashed p-6 text-center"><Upload/><b className="mt-2 text-[14px] text-[#616161]">Attach photo or document</b></div><div className="mt-3 inline-flex items-center gap-2 rounded-lg border border-[#2e7d32] bg-[#e8f5e9] p-3 text-[14px] font-semibold text-[#2e7d32]">screenshot_err.jpg <span>×</span></div></div><div className="opacity-50"><div className="mb-2 text-[10px] font-bold">PRIORITY (ADMIN ONLY)</div><div className="flex h-12 items-center justify-between rounded-xl border bg-[#f5f5f5] px-4">Normal<span>🔒</span></div></div></Card><button onClick={()=>setSubmitted(true)} className="w-full rounded-xl bg-[#2e7d32] py-3 text-[16px] font-bold text-white">Submit Ticket</button></div>{submitted&&<div className="fixed inset-0 grid place-items-center bg-black/40 p-10"><div className="w-full rounded-xl bg-white p-5 text-center"><div className="mx-auto grid size-20 place-items-center rounded-full bg-[#e8f5e9]"><Check className="size-10 text-[#2e7d32]"/></div><h2 className="mt-6 text-[20px] font-bold">Ticket #T-1234 Created</h2><p className="mt-2 text-[14px] text-[#616161]">We've received your request and will respond within 24 hours.</p><button onClick={()=>setSubmitted(false)} className="mt-5 w-full rounded-xl bg-[#2e7d32] py-3 font-bold text-white">Done</button><div className="mt-4 font-semibold text-[#2e7d32]">View My Tickets</div></div></div>}</Shell>}

export function TicketDetails({onBack}:Props){return <Shell><StatusBar/><Header title="Ticket #T-1234" onBack={onBack} right={<span className="rounded-full bg-orange-50 px-3 py-1 text-[10px] font-bold text-[#ffa000]">OPEN</span>}/><div className="border-b bg-white p-4 text-[14px] font-semibold text-[#616161]">Technical Issue | High | Created 20 Jun 2025</div><div className="flex flex-1 flex-col gap-5 overflow-hidden p-4"><div className="flex items-end gap-2"><div className="grid size-8 place-items-center rounded-full bg-[#eee] text-[10px] text-[#616161]">S</div><div><div className="mb-1 text-[10px] font-bold text-[#616161]">Support Agent</div><div className="max-w-[260px] rounded-b-2xl rounded-tr-2xl bg-white p-3"><p className="text-[16px] leading-6">We are looking into your issue. Could you provide the transaction ID for the Teja Chilli listing?</p><div className="pt-1 text-right text-[10px] font-bold text-[#9e9e9e]">10:45 AM</div></div></div></div><div className="flex justify-end"><div className="max-w-[260px] rounded-b-2xl rounded-tl-2xl border border-[#2e7d32] bg-[#e8f5e9] p-3"><p className="text-[16px] leading-6">Sure, it is TRD-123456789. Also, I uploaded the contract PDF earlier.</p><div className="pt-1 text-right text-[10px] font-bold text-[#616161]">10:50 AM ✓✓</div></div></div></div><div className="border-t bg-white p-3"><div className="flex gap-3"><div className="grid size-10 place-items-center"><Paperclip/></div><div className="flex-1 rounded-full bg-[#f5f5f5] px-4 py-2 text-[16px] text-[#616161]">Add a reply...</div><button className="grid size-10 place-items-center rounded-full bg-[#2e7d32] text-white"><Send/></button></div><div className="pt-2 text-center text-[14px] font-semibold text-[#9e9e9e]">Resolve Ticket</div></div><BottomIndicator/></Shell>}

export function HelpCenter(){return <Shell><StatusBar/><Header title="Help Center" right={<span>○</span>}/><div className="space-y-5"><div className="px-5"><div className="flex h-12 w-[100px] items-center gap-2 rounded-xl border bg-white px-4"><Search className="size-5 text-[#616161]"/><span className="truncate text-[16px] text-[#616161]">Se...</span></div></div><div className="flex gap-2 overflow-hidden px-5">{['How to tokenize','Bidding rules','Payment','KYC'].map((x,i)=><span key={x} className={`shrink-0 rounded-full px-4 py-2 text-[14px] font-semibold ${i===0?'bg-[#2e7d32] text-white':'bg-[#eee] text-[#616161]'}`}>{x}</span>)}</div><div className="space-y-0"><div className="rounded-t-xl bg-white"><div className="flex items-center justify-between bg-[#e8f5e9] p-5 text-[#2e7d32]"><b>Getting Started</b><ChevronDown/></div><div>{['How to register as a producer?','What is KYC?'].map(x=><div key={x} className="flex items-center justify-between border-b p-5"><b className="text-[14px]">{x}</b><ChevronRight className="text-[#9e9e9e]"/></div>)}</div></div>{['Trading','Finance'].map(x=><div key={x} className="flex items-center justify-between border-b bg-white p-5 text-[16px] font-bold">{x}<ChevronRight className="text-[#9e9e9e]"/></div>)}</div><div><div className="flex items-center justify-between px-5"><b>Video Tutorials</b><span className="font-semibold text-[#2e7d32]">View all</span></div><div className="mt-3 flex gap-4 overflow-hidden px-5">{[1,2].map(i=><div key={i} className="w-[220px] shrink-0"><div className="grid h-[124px] place-items-center rounded-xl bg-black text-white">▷</div><div className="mt-2 text-[14px] font-semibold">How to bid on commodities</div></div>)}</div></div><div className="p-5 text-center"><p className="text-[14px] text-[#616161]">Need more help?</p><button className="mt-3 w-full rounded-xl bg-[#2e7d32] py-3 text-[16px] font-bold text-white">Contact Support</button></div><BottomIndicator/></div></Shell>}

export function Settings(){return <Shell><StatusBar/><Header title="Settings"/><div className="space-y-5 p-5"><Card className="p-4"><div className="flex items-center justify-between"><div><div className="font-semibold">Rajesh Kumar</div><div className="text-[12px] text-[#616161]">Producer – Guntur</div></div><span className="font-semibold text-[#2e7d32]">Edit</span></div></Card><div><h3 className="mb-2 text-[12px] font-bold text-[#616161]">NOTIFICATIONS</h3><Card className="divide-y"><SettingRow label="Push Notifications" on/><SettingRow label="SMS Alerts" on/><SettingRow label="Whatsapp Updates" on/><SettingRow label="Email Statements" on={false}/></Card></div><div><h3 className="mb-2 text-[12px] font-bold text-[#616161]">SECURITY</h3><Card className="divide-y"><SettingNav label="Change Password"/><SettingNav label="Two-Factor Authentication"/></Card></div><div><h3 className="mb-2 text-[12px] font-bold text-[#616161]">APP PREFERENCES</h3><Card className="divide-y"><SettingNav label="Language" value="English (India)"/><SettingRow label="Dark Mode" on={false}/></Card></div><div><h3 className="mb-2 text-[12px] font-bold text-[#616161]">LEGAL</h3><Card className="divide-y"><SettingNav label="Terms of Service"/><SettingNav label="Privacy Policy"/></Card></div><button className="w-full rounded-xl border border-red-300 bg-white py-3 font-semibold text-red-500">Delete Account</button><button className="w-full rounded-xl border border-red-300 bg-white py-3 font-semibold text-red-500">Logout</button></div><BottomIndicator/></Shell>}

export const supportRoutes: Record<string, React.ComponentType<any>> = {"support-search": GlobalSearch,"support-notifications": Notifications,"support-call": VoiceCall,"support-documents": Documents,"support-qr": QRScanner,"support-help": HelpCenter,"support-raise": SupportTicket,"support-ticket": TicketDetails,"support-settings": Settings};
