import React from "react";

type Props = { onBack?: () => void };

const B = "#1565c0";
const G = "#2e7d32";
const BG = "#f5f5f5";
const TEXT = "#212121";
const MUTED = "#757575";
const BORDER = "#e0e0e0";

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="mx-auto flex min-h-screen w-full max-w-[375px] flex-col overflow-hidden bg-[#f5f5f5] text-[#212121]">{children}</div>;
}
function StatusBar(){return <div className="flex items-center justify-between px-6 pb-2 pt-3 text-[14px] font-semibold"><span>9:41</span><span className="text-[12px] text-[#212121]">▮▮▮ ◉ ▣</span></div>}
function Header({title,onBack,right}:{title:string;onBack?:()=>void;right?:React.ReactNode}){return <div className="flex items-center justify-between px-4 py-3"><button onClick={onBack} className="text-2xl leading-none">←</button><h1 className="text-[20px] font-bold">{title}</h1><div className="grid size-8 place-items-center">{right}</div></div>}
function BottomNav({active="Home"}:{active?:string}){const items=["Home","Bookings","Trips","Wallet","More"];return <><div className="mt-auto flex h-[72px] items-center justify-between border-t border-[#eee] bg-white px-3">{items.map(x=><div key={x} className={`w-[62px] text-center text-[10px] ${active===x?"font-semibold text-[#1565c0]":"text-[#757575]"}`}><div className="mb-1 text-[20px]">{x==="Home"?"⌂":x==="Bookings"?"▣":x==="Trips"?"◫":x==="Wallet"?"▤":"☰"}</div>{x}</div>)}</div><div className="flex h-[26px] items-center justify-center bg-white"><div className="h-[4px] w-[134px] rounded-full bg-black/70"/></div></>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl bg-white ${className}`}>{children}</div>}
function Stat({label,value,tone="blue"}:{label:string;value:string;tone?:"blue"|"green"|"orange"}){const c=tone==="green"?G:tone==="orange"?"#ff8f00":B;return <div className="flex-1 rounded-2xl bg-white p-4"><div className="text-[12px] text-[#757575]">{label}</div><div className="mt-1 text-[20px] font-bold" style={{color:c}}>{value}</div></div>}
function OTPBoxes(){return <div className="flex gap-2">{["4","","","","",""] .map((x,i)=><div key={i} className={`flex h-14 w-11 items-center justify-center rounded-lg border ${i===0?"border-2 border-[#1565c0]":"border-[#e0e0e0]"} bg-white text-[24px] font-bold`}>{x}{i===1&&<div className="h-6 w-0.5 bg-[#1565c0]"/>}</div>)}</div>}

export function TransporterDashboard({onBack}:Props){return <Shell><StatusBar/><div className="space-y-5 px-4 pb-4"><div className="flex items-start justify-between"><div><h2 className="text-[20px] font-bold">Hello, Mahesh</h2><p className="text-[14px] text-[#757575]">Ready for the next haul?</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-[11px] font-bold text-[#1565c0]">1,250 TRD</span><span>♧</span><div className="size-10 rounded-full bg-[#ddd]"/></div></div><div className="flex gap-3 overflow-hidden"><Stat label="Active Trips" value="2"/><Stat label="Completed" value="15" tone="green"/><Stat label="Earnings" value="₹45k"/></div><Card className="flex items-center justify-between border border-[#e0e0e0] p-4"><span className="font-semibold">• Available for bookings</span><span className="text-[14px] text-[#757575]">Change Status</span></Card><div><h3 className="mb-3 text-[18px] font-bold">Active Trips</h3><Card className="p-4 shadow-[0_4px_6px_rgba(0,0,0,.08)]"><div className="flex items-center justify-between"><span className="text-[14px] font-bold text-[#757575]">TRIP #772</span><span className="rounded bg-blue-50 px-2 py-1 text-[10px] font-bold text-[#1565c0]">IN TRANSIT</span></div><div className="my-4 rounded-lg bg-[#fafafa] p-3"><div className="text-[14px]">Guntur Farm</div><div className="my-3 text-center text-[#1565c0]">↓</div><div className="text-[14px]">Guntur Market Yard</div></div><div className="flex items-center justify-between border-t pt-3 text-[12px] text-[#757575]"><span>Commodity<br/><b className="text-[#212121]">Chilli • 2,500 kg</b></span><span className="text-right">ETA<br/><b className="text-[#1565c0]">30 min</b></span></div><div className="mt-3 flex gap-3"><button className="flex-1 rounded-xl border border-[#26a69a] py-3 text-[14px] font-semibold text-[#26a69a]">Track</button><button className="flex-1 rounded-xl py-3 text-[14px] font-semibold text-[#757575]">Contact</button></div></Card></div><Card className="bg-[#1565c0] p-4 text-white"><div className="text-[12px] opacity-80">AI Suggested Booking</div><div className="text-[16px] font-bold">Haul 50 bags Tenali → Guntur</div><div className="text-[14px] font-semibold">Payout: ₹3,500</div><button className="mt-4 w-full rounded-xl bg-[#1976d2] py-3 font-semibold">Accept</button></Card></div><BottomNav active="Home"/></Shell>}

export function AvailableLoads({onBack}:Props){return <Shell><StatusBar/><Header title="Available Loads" onBack={onBack} right={<span>☷</span>}/><div className="flex gap-2 overflow-hidden px-4 pb-3">{['Route','Commodity','Weight','Price'].map(x=><span key={x} className="rounded-full border bg-white px-3 py-2 text-[12px]">{x}⌄</span>)}</div><div className="space-y-4 p-4">{[1,2,3].map(i=><Card key={i} className="border border-[#e0e0e0] p-4"><div className="text-[16px] font-bold">Priya Agencies (CA)</div><div className="text-[14px] text-[#757575]">Tenali → Guntur (12 km)</div><div className="mt-4 flex items-end justify-between"><div><div className="text-[12px] text-[#757575]">Load</div><b>Chilli, 50 bags</b></div><div className="text-right"><div className="text-[12px] text-[#757575]">Payout</div><b className="text-[#1565c0]">₹3,500</b></div></div><button className="mt-4 w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">Accept</button></Card>)}<div className="py-8 text-center"><div className="mx-auto mb-2 size-28 bg-[#ffe9ad] p-4">🚚</div><div className="text-[13px] text-[#757575]">That's all for today. Check back later!</div></div></div><BottomNav active="Bookings"/></Shell>}

function OTPPage({title,subtitle,destination,delivery=false,onBack}:Props&{title:string;subtitle:string;destination:string;delivery?:boolean}){return <Shell><StatusBar/><Header title={title} onBack={onBack}/><div className="flex flex-col items-center gap-8 p-6 pt-8"><div className="grid size-20 place-items-center rounded-full bg-blue-50 text-4xl text-[#1565c0]">{delivery?'▧':'×'}</div><div className="text-center"><h2 className="text-[24px] font-bold text-black">{title}</h2><p className="mt-2 text-[15px] text-[#757575]">{subtitle}</p></div><Card className="w-full border p-4"><div className="text-[12px] uppercase text-[#757575]">{delivery?'Deliver to':'Pickup from'}</div><div className="font-bold">{destination}</div></Card><OTPBoxes/><div className="w-full space-y-4"><button className="w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">{delivery?'Confirm Delivery':'Confirm Pickup'}</button><button className="w-full py-3 font-semibold text-[#757575]">Resend OTP</button>{delivery&&<button className="w-full rounded-xl border border-red-500 py-2 text-sm font-semibold text-red-500">Damage or shortage? Report Issue</button>}</div></div><div className="mt-auto h-8"/></Shell>}
export function ConfirmPickup(p:Props){return <OTPPage {...p} title="Confirm Pickup" subtitle="Ask consignor (producer/CA) for OTP to confirm pickup" destination="Guntur Farm, Unit 4"/>}
export function ConfirmDelivery(p:Props){return <OTPPage {...p} title="Confirm Delivery" subtitle="Ask receiver for OTP to confirm delivery" destination="Guntur Market Yard, Gate 2" delivery/>}

export function LiveTracking({onBack}:Props){return <Shell><div className="h-[380px] bg-[#dbeafe] p-4"><div className="rounded-full bg-white p-2 w-fit">←</div><div className="mt-32 flex justify-center"><span className="rounded-full bg-[#1565c0] px-4 py-2 font-bold text-white">• In Transit</span></div></div><Card className="-mt-5 rounded-t-[24px] p-5"><div className="flex items-center justify-between"><div><div className="text-[14px] text-[#757575]">Est. Arrival</div><div className="text-[20px] font-bold text-[#1565c0]">1:40 PM</div></div><div className="text-[14px] text-[#757575]">Share Live Location <span className="ml-2 inline-block h-6 w-11 rounded-full bg-[#1565c0] align-middle"/></div></div><div className="my-5 space-y-5"><div>✓ <b className="ml-3">Pickup completed</b><div className="ml-7 text-xs text-[#757575]">10:20 AM</div></div><div>✓ <b className="ml-3">Left warehouse</b><div className="ml-7 text-xs text-[#757575]">10:50 AM</div></div><div>● <b className="ml-3">Reached Toll Naka</b><div className="ml-7 text-xs text-[#757575]">ETA 1:40 PM</div></div></div><button className="w-full rounded-xl border border-red-500 py-3 font-semibold text-red-500">Report Issue</button></Card></Shell>}

export function TripHistory({onBack}:Props){const trips=['TRIP #772','TRIP #768','TRIP #755'];return <Shell><StatusBar/><Header title="Trip History" onBack={onBack}/><div className="space-y-4 p-4"><Card className="p-4"><div className="flex justify-between text-[14px] text-[#757575]"><span>Earnings Trend</span><b className="text-[#1565c0]">₹18,400</b></div><div className="mt-4 flex h-20 items-end justify-between">{[20,45,30,60,50,80,70].map((h,i)=><div key={i} className="w-8 bg-blue-50" style={{height:h}}/>)}</div></Card><div className="flex gap-2">{['All','This week','This month'].map((x,i)=><span key={x} className={`rounded-full px-3 py-2 text-[12px] ${i===0?'bg-[#1565c0] text-white':'border bg-white'}`}>{x}</span>)}</div>{trips.map(t=><Card key={t} className="p-4"><div className="flex justify-between"><span className="text-[14px] text-[#757575]">{t}</span><span className="text-[#ff8f00]">☆☆☆☆☆</span></div><div className="mt-3">Guntur → Tenali</div><div className="text-xs text-[#757575]">Chilli • 2,500 kg • 12 Jan</div><div className="mt-3 flex justify-between border-t pt-3"><b className="text-[#1565c0]">₹3,500</b><span>›</span></div></Card>)}</div><BottomNav active="Trips"/></Shell>}

export function CompleteKYC({onBack}:Props){return <Shell><StatusBar/><Header title="Complete KYC" onBack={onBack}/><div className="space-y-8 p-6"><div><div className="flex justify-between text-xs text-[#757575]"><span>Profile Verification</span><span className="text-[#1565c0]">1/3 Complete</span></div><div className="mt-2 h-1 rounded bg-[#eee]"/></div><div className="space-y-5"><div className="flex gap-4"><div className="grid size-6 place-items-center rounded-full bg-[#2e7d32] text-white">✓</div><div><b>Mobile & Email OTP</b><div className="text-xs text-[#757575]">Verified on 10 Jan 2026</div></div></div><div className="flex gap-4"><div className="grid size-6 place-items-center rounded-full border-2 border-[#1565c0] text-[#1565c0]">•</div><div className="flex-1"><div className="flex justify-between"><div><b>License & Facial Scan</b><div className="text-xs text-[#757575]">Required for transit permits</div></div><button className="rounded bg-[#1565c0] px-4 py-2 text-[10px] font-semibold text-white">START</button></div></div></div><div className="flex gap-4 text-[#bdbdbd]"><div className="grid size-6 place-items-center rounded-full bg-[#eee]">⌕</div><div><b>Physical Verification</b><div className="text-xs">Schedule after completing Step 2</div></div></div></div><button className="w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">Complete KYC</button></div><div className="mt-auto h-8"/></Shell>}

export function MyVehicles({onBack}:Props){const vehicles=[['AP 07 TX 4545','Tata Ace','1,500 kg','12 Oct 2026'],['AP 07 TY 8821','Ashok Leyland','3,000 kg','05 Mar 2026']];return <Shell><StatusBar/><Header title="My Vehicles" onBack={onBack} right={<span className="grid size-8 place-items-center rounded-full bg-blue-50 text-[#1565c0]">+</span>}/><div className="space-y-4 p-4">{vehicles.map(v=><Card key={v[0]} className="p-4"><div className="flex justify-between"><b>{v[0]}</b><span className="rounded bg-green-50 px-2 py-1 text-[10px] font-bold text-[#2e7d32]">Verified</span></div><div className="mt-4 flex gap-7 text-sm"><div><div className="text-xs text-[#757575]">Vehicle Type</div>{v[1]}</div><div><div className="text-xs text-[#757575]">Capacity</div>{v[2]}</div></div><div className="my-3 border-t pt-3 text-xs text-[#757575]">Insurance Expires: <b className="text-[#212121]">{v[3]}</b></div><div className="grid grid-cols-3 gap-2">{['RC','Insurance','Fitness'].map(x=><span key={x} className="rounded-lg bg-[#f5f5f5] py-2 text-center text-[10px]">✓ {x}</span>)}</div></Card>)}</div><BottomNav active="More"/></Shell>}

export function MyEarnings({onBack}:Props){return <Shell><StatusBar/><Header title="My Earnings" onBack={onBack} right={<span>⇩</span>}/><div className="space-y-4 p-4"><Card className="flex justify-between p-5"><Stat label="Total Earned" value="₹4.5L"/><Stat label="Paid Out" value="₹4.1L" tone="green"/><Stat label="Pending" value="₹40k" tone="orange"/></Card><div><div className="mb-2 text-[14px] text-[#757575]">Recent Transactions</div><Card>{[['T-772','12 Jan','₹3,500','Paid'],['T-768','10 Jan','₹4,200','Paid'],['T-760','08 Jan','₹2,800','Pending']].map(r=><div key={r[0]} className="flex items-center justify-between border-b p-4 last:border-0"><div><b>{r[0]}</b><div className="text-xs text-[#757575]">{r[1]}</div></div><div className="flex items-center gap-3"><b>{r[2]}</b><span className={`rounded px-2 py-1 text-[10px] font-bold ${r[3]==='Paid'?'bg-green-50 text-[#2e7d32]':'bg-amber-50 text-[#ff8f00]'}`}>{r[3]}</span></div></div>)}</Card></div><button className="w-full rounded-xl border-2 border-[#1565c0] py-3 font-semibold text-[#1565c0]">Request Payout</button><div className="text-[10px] text-[#757575]">External payout to registered bank account</div></div><BottomNav active="Wallet"/></Shell>}

export function MyDrivers({onBack}:Props){const drivers=[['Ramesh Kumar','DL-4545920','Active','94% Score'],['Suresh Babu','DL-8821033','Active','88% Score'],['Mohan Lal','DL-1200445','Inactive','72% Score']];return <Shell><StatusBar/><Header title="My Drivers" onBack={onBack} right={<span className="grid size-8 place-items-center rounded-full bg-blue-50 text-[#1565c0]">+</span>}/><div className="space-y-3 p-4">{drivers.map(d=><Card key={d[0]} className="flex items-center gap-4 p-4"><div className="size-12 rounded-full bg-[#f1f1f1]"/><div className="min-w-0 flex-1"><div className="flex justify-between"><b>{d[0]}</b><span className={`rounded px-2 py-1 text-[10px] ${d[2]==='Active'?'bg-green-50 text-[#2e7d32]':'bg-[#eee] text-[#757575]'}`}>{d[2]}</span></div><div className="text-xs text-[#757575]">Lic: {d[1]}</div><div className="mt-2 flex items-center gap-2"><div className="h-1 w-24 rounded bg-[#eee]"/><span className="text-[10px] text-[#757575]">{d[3]}</span></div></div></Card>)}</div><BottomNav active="More"/></Shell>}

export function AvailableLoads2({onBack}:Props){return <AvailableLoads onBack={onBack}/>}
export function Ratings({onBack}:Props){return <Shell><StatusBar/><Header title="My Ratings" onBack={onBack}/><div className="space-y-4 p-4"><Card className="flex items-center justify-between p-6"><div><div className="flex items-center gap-2"><span className="text-[40px] font-bold">4.8</span><span className="text-2xl text-[#1565c0]">☆</span></div><div className="text-sm text-[#757575]">245 total reviews</div></div><div className="w-36 space-y-2 text-[10px]">{[['Punctuality','4.9'],['Care of Goods','4.7'],['Communication','4.8']].map(x=><div key={x[0]}><div className="flex justify-between"><span>{x[0]}</span><b>{x[1]}</b></div><div className="h-1 rounded bg-[#eee]"/></div>)}</div></Card><Card className="bg-blue-50 p-4 text-[#0d47a1]"><div className="font-semibold text-[#1565c0]">✣ AI Improvement Tip</div><div className="mt-1 text-sm">Improve care of goods score by using vertical stacking for jute bags as recommended in loading orders.</div></Card><div className="text-[14px] font-semibold text-[#757575]">Recent Reviews</div>{[1,2].map(i=><Card key={i} className="p-4"><div className="flex justify-between"><b>Commission Agent</b><span className="text-xs text-[#757575]">12 Jan</span></div><div className="my-2 text-[#ff8f00]">☆☆☆☆☆</div><div className="text-sm text-[#757575]">Excellent handling of sensitive chilli bags. Reached before time. Highly recommended transporter.</div></Card>)}</div><BottomNav active="More"/></Shell>}

export function TripDetails({onBack}:Props){return <Shell><StatusBar/><Header title="Trip Details" onBack={onBack}/><div className="space-y-4 p-4"><Card className="p-4"><div className="space-y-4"><div><span className="text-xs text-[#757575]">Pickup</span><div className="font-semibold">Guntur Farm</div></div><div><span className="text-xs text-[#757575]">Drop</span><div className="font-semibold">Guntur Market Yard</div></div></div><div className="mt-4 flex justify-between border-t pt-3 text-sm"><span className="text-[#757575]">12 km • 45 min est.</span><b className="text-[#1565c0]">₹3,500 Total</b></div></Card><div className="text-[14px] font-bold uppercase text-[#757575]">Commodity Info</div><Card className="space-y-3 p-4"><div className="flex justify-between"><span className="text-[#757575]">Item</span><b>Chilli (Dry)</b></div><div className="flex justify-between"><span className="text-[#757575]">Weight/Bags</span><b>2,500 kg (50 Jute Bags)</b></div></Card><Card className="border border-[#ffa000] bg-[#fff8e1] p-4"><b className="text-[#ffa000]">ⓘ Special Instructions</b><div className="mt-2 text-sm">Load last destination first (unload at yard). Ensure jute bags are stacked vertically.</div></Card><button className="w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">Accept Trip</button><div className="text-center text-xs text-[#757575]">Accepting implies you agree to TRADIE logistics terms.</div></div></Shell>}

export function LoadingOrder({onBack}:Props){return <Shell><StatusBar/><Header title="Loading Order" onBack={onBack}/><div className="bg-blue-50 p-4 text-sm text-[#0d47a1]">ⓘ Load bags in the order shown. Last destination loaded first for optimized unloading.</div><div className="space-y-3 p-4">{[['1','Guntur Market Yard','LOAD FIRST'],['2','Tenali Warehouse','LOAD SECOND'],['3','Vijayawada','LOAD LAST']].map(r=><Card key={r[0]} className="flex items-center gap-4 border p-4"><div className="grid size-7 place-items-center rounded-full bg-[#eee] text-xs font-bold">{r[0]}</div><div><b>{r[1]}</b><div className={`text-[11px] font-bold ${r[2]==='LOAD LAST'?'text-[#2e7d32]':'text-[#1565c0]'}`}>{r[2]}</div></div></Card>)}<div className="pt-2 text-[12px] font-bold uppercase text-[#757575]">Safety Checklist</div>{['Loaded bag count matches (50 bags)','QR code attached to consignment'].map(x=><div key={x} className="flex items-center gap-3 text-sm"><span className="size-5 rounded bg-[#1565c0]"/> {x}</div>)}</div><div className="mt-auto p-4"><button className="w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">Confirm Loading</button></div></Shell>}

export function TransportPermit({onBack}:Props){return <Shell><StatusBar/><Header title="Transport Permit" onBack={onBack}/><div className="flex flex-col items-center gap-8 p-5 pt-10"><div className="rounded-[24px] border-2 border-dashed border-[#1565c0] bg-white p-5"><div className="size-48 bg-[#0b1430] grid place-items-center text-5xl text-cyan-300">▦</div></div><Card className="w-full p-5"><div className="flex justify-between text-sm"><span className="text-[#757575]">Permit Number</span><b>TRP-20250620-001</b></div><div className="mt-4 flex justify-between text-sm"><span className="text-[#757575]">Vehicle Number</span><b>AP28AB1234</b></div><div className="mt-4 flex justify-between text-sm"><span className="text-[#757575]">Commodity</span><b>Chilli, 2,500 kg</b></div><div className="my-4 border-t"/><div className="text-sm"><div className="text-[#757575]">Validity</div><b className="text-red-500">Valid until 21 Jun 2025 10:00 AM</b></div></Card></div><div className="mt-auto space-y-3 p-5"><div className="flex gap-3"><button className="flex-1 rounded-xl border-2 border-[#1565c0] py-3 font-semibold text-[#1565c0]">Download PDF</button><button className="flex-1 rounded-xl py-3 font-semibold text-[#757575]">Share</button></div><button className="w-full rounded-xl bg-[#1565c0] py-3 font-semibold text-white">Start Trip</button></div></Shell>}

export const transporterRoutes: Record<string, React.ComponentType<Props>> = {
  "transporter-dashboard": TransporterDashboard,
  "transporter-loads": AvailableLoads,
  "transporter-trip-details": TripDetails,
  "transporter-loading-order": LoadingOrder,
  "transporter-live-tracking": LiveTracking,
  "transporter-permit": TransportPermit,
  "transporter-pickup": ConfirmPickup,
  "transporter-delivery": ConfirmDelivery,
  "transporter-trip-history": TripHistory,
  "transporter-kyc": CompleteKYC,
  "transporter-vehicles": MyVehicles,
  "transporter-earnings": MyEarnings,
  "transporter-drivers": MyDrivers,
  "transporter-ratings": Ratings,
};
