import React from "react";

type BackProps = { onBack?: () => void };

const C = {
  bg: "#f1f5f9",
  text: "#1e293b",
  muted: "#64748b",
  border: "#e2e8f0",
  green: "#558b2f",
  greenBg: "#f1f8e9",
  orange: "#ff8f00",
  amber: "#ffb300",
  red: "#ef4444",
  blue: "#2196f3",
  slate: "#cbd5e1",
  white: "#ffffff",
};

const mobileFrame = "mx-auto flex min-h-screen w-full max-w-[375px] flex-col overflow-hidden bg-[#f1f5f9] text-[#1e293b]";

function Shell({ children }: { children: React.ReactNode }) {
  return <div className={mobileFrame}>{children}</div>;
}
function StatusBar() {
  return <div className="flex h-11 items-center justify-between px-5 text-[14px] font-semibold"><span>9:41</span><div className="flex items-center gap-2 text-[#1e293b]">▮▮▮ ◉ ▣</div></div>;
}
function BackHeader({ title, onBack, right }: { title: string; onBack?: () => void; right?: React.ReactNode }) {
  return <div className="flex items-center justify-between px-4 py-3"><div className="flex items-center gap-4"><button onClick={onBack} className="text-2xl leading-none" aria-label="Back">←</button><h1 className="text-[20px] font-bold">{title}</h1></div><div>{right}</div></div>;
}
function BottomNav({ active = "Home" }: { active?: string }) {
  const items = ["Home", "Entry", "Auctions", "Weigh", "Reports"];
  return <><div className="mt-auto flex h-[72px] items-center justify-between border-t border-[#e2e8f0] bg-white px-4">{items.map((x)=><div key={x} className={`w-[60px] text-center text-[11px] ${active===x?"font-semibold text-[#558b2f]":"text-[#64748b]"}`}><div className="mb-1 text-[20px]">{x==="Home"?"⌂":x==="Entry"?"⌑":x==="Auctions"?"⚒":x==="Weigh"?"⊗":"◫"}</div>{x}</div>)}</div><div className="flex h-[34px] items-start justify-center bg-white pb-2 pt-4"><div className="h-[5px] w-[134px] rounded-[10px] bg-[#1e293b]"/></div></>;
}
function Card({ children, className="" }: {children: React.ReactNode; className?:string}) { return <div className={`rounded-xl bg-white ${className}`}>{children}</div>; }
function Stat({label,value,tone="green",sub}:{label:string;value:string;tone?:"green"|"orange"|"red";sub?:string}) { const border=tone==="green"?C.green:tone==="orange"?C.amber:C.red; return <div className="flex-1 rounded-lg bg-white p-3" style={{borderLeft:`3px solid ${border}`}}><div className="text-[11px] text-[#64748b]">{label}</div><div className="mt-1 text-[16px] font-bold">{value}<span className="ml-1 text-[11px] font-semibold text-[#10b981]">{sub}</span></div></div>; }

export function YardDashboardScreen({onBack}:BackProps){return <Shell><StatusBar/><div className="flex items-center justify-between px-4 py-3"><div><div className="text-[20px] font-bold">Guntur Market Yard</div><div className="text-[14px] text-[#64748b]">20 Jun 2025</div></div><div className="text-[24px]">♧</div></div><div className="flex gap-3 overflow-hidden px-4 pb-5"><Stat label="Vehicles in Queue" value="8"/><Stat label="Lots Awaiting" value="12"/><Stat label="Active Auctions" value="3"/><Stat label="Tax Collected" value="₹1,25,000"/></div><div className="space-y-4 px-4"><div className="flex items-center justify-between"><h2 className="text-[18px] font-semibold">Live Queue Summary</h2><span className="text-[14px] font-semibold text-[#558b2f]">View All</span></div><Card className="p-4"><div className="flex items-start justify-between"><div><div className="text-[14px] font-semibold">AP28AB1234 • Chilli</div><div className="text-[11px] text-[#64748b]">Producer: Rajesh • CA: Priya Agencies</div></div><span className="rounded bg-[#fff8e1] px-2 py-1 text-[11px] font-semibold uppercase text-[#ffb300]">Waiting</span></div><div className="mt-4 flex items-center justify-between"><div className="text-[14px] font-semibold">120 MT</div><div className="text-[11px] text-[#64748b]">15 min waiting</div><button className="rounded-lg bg-[#558b2f] px-5 py-3 text-[14px] font-semibold text-white">Process</button></div></Card><div className="flex items-center gap-2 border border-[#ff8f00] bg-[#fff3e0] p-3 text-[14px] text-[#ff8f00]">ⓘ Tax Alert: Overdue payments from 4 buyers.</div><div className="pt-1"><h2 className="mb-4 text-[18px] font-semibold">Quick Actions</h2><div className="grid grid-cols-4 gap-4">{["Gate Entry","Auction","Weighbridge","Reports"].map(x=><div key={x} className="text-center"><div className="mx-auto mb-2 grid size-14 place-items-center rounded-xl border border-[#e2e8f0] bg-white text-2xl">{x==="Gate Entry"?"▣":x==="Auction"?"▦":x==="Weighbridge"?"⊗":"▤"}</div><div className="text-[11px]">{x}</div></div>)}</div></div></div><BottomNav/></Shell>}

export function TaxCollectionScreen({onBack}:BackProps){const rows=[['B-234','Sri Ram Traders','₹4,500','OVERDUE'],['B-235','Jai Kisan Ent.','₹12,200','PENDING'],['B-236','Kiran Exports','₹8,000','PAID']];return <Shell><StatusBar/><BackHeader title="Tax Collection" onBack={onBack}/><div className="flex gap-3 px-4 pb-6"><Stat label="Collected" value="₹1.25L"/><Stat label="Pending" value="₹25K" tone="orange"/><Stat label="Overdue" value="₹5K" tone="red"/></div><div><div className="grid grid-cols-[60px_1fr_80px] bg-[#cbd5e1] p-3 text-[11px] font-bold"><div>BILL #</div><div>BUYER</div><div className="text-right">DUE</div></div>{rows.map(([bill,buyer,due,status])=><div key={bill} className="border-b border-[#e2e8f0] bg-white p-3"><div className="grid grid-cols-[60px_1fr_80px] items-center text-[14px]"><div className="font-semibold">{bill}</div><div>{buyer}</div><div className="text-right font-semibold">{due}</div></div><div className="mt-3 flex items-center justify-between"><span className={`rounded px-2 py-1 text-[11px] font-semibold ${status==='PAID'?'bg-[#f1f8e9] text-[#558b2f]':status==='OVERDUE'?'bg-[#fff3e0] text-[#ff8f00]':'bg-[#fff8e1] text-[#ffb300]'}`}>{status}</span>{status!=='PAID'&&<button className="rounded border border-[#558b2f] px-3 py-1 text-[11px] font-bold text-[#558b2f]">Record Payment</button>}</div></div>)}</div><div className="p-4"><button className="w-full rounded-lg bg-[#1e293b] py-3 text-[14px] font-semibold text-white">⊗ Generate Tax Report</button></div><BottomNav active="Reports"/></Shell>}

export function StateOverviewScreen({onBack}:BackProps){const bars=[['Chilli','204'],['Cotton','166'],['Turmeric','115'],['Onion','77'],['Paddy','64']];return <Shell><StatusBar/><div className="px-4 py-3"><h1 className="text-[20px] font-bold">Andhra Pradesh Overview</h1></div><div className="flex gap-3 px-4 pb-5"><Stat label="Trade Volume" value="28.4K MT" sub="↑ 12%"/><Stat label="Revenue" value="₹2.4 Cr" sub="↑ 8%"/><Stat label="Active Yards" value="42"/></div><Card className="mx-0 border border-[#e2e8f0] p-4"><h2 className="text-[14px] font-bold">Volume by Commodity (MT)</h2><div className="mt-4 space-y-3">{bars.map(([label,w])=><div key={label} className="flex items-center gap-3"><div className="w-[60px] text-[11px] text-[#64748b]">{label}</div><div className="h-4 flex-1 rounded bg-[#f1f5f9]"><div className="h-full bg-[#558b2f]" style={{width:`${w}px`}}/></div></div>)}</div></Card><div className="p-4"><h2 className="mb-3 text-[14px] font-bold">Tax Revenue by District</h2><div className="h-[140px] rounded-lg border border-[#cbd5e1] bg-white"/></div><BottomNav active="Reports"/></Shell>}

export function DailyArrivalReportScreen({onBack}:BackProps){const rows=[['Chilli','120 MT','Guntur','Priya Agencies','08:30'],['Turmeric','80 MT','Nizamabad','Krishna Traders','09:15'],['Cotton','200 MT','Adilabad','Ravi & Co','10:00'],['Onion','80 MT','Kurnool','Lakshmi Agencies','11:30']];return <Shell><StatusBar/><BackHeader title="Daily Arrival Report" onBack={onBack}/><div className="mx-4 mb-4 flex items-center justify-between rounded-xl border bg-white p-3"><span>‹</span><span className="font-semibold">◷ 20 Jun 2025</span><span>›</span></div><div className="flex gap-3 px-4 pb-5"><Stat label="Total Arrivals" value="24 lots"/><Stat label="Total Weight" value="480 MT"/></div><div className="text-[11px]"><div className="grid grid-cols-[70px_55px_70px_1fr_40px] bg-[#cbd5e1] p-3 font-bold"><div>COMMODITY</div><div>QTY(MT)</div><div>ORIGIN</div><div>CA</div><div className="text-right">TIME</div></div>{rows.map(r=><div key={r[0]} className="grid grid-cols-[70px_55px_70px_1fr_40px] border-b border-[#e2e8f0] bg-white p-3"><div className="font-semibold">{r[0]}</div><div>{r[1]}</div><div className="text-[#64748b]">{r[2]}</div><div className="truncate text-[#64748b]">{r[3]}</div><div className="text-right text-[#64748b]">{r[4]}</div></div>)}</div><div className="flex justify-end gap-3 p-4"><button className="rounded border border-[#558b2f] bg-[#f1f8e9] px-4 py-2 text-[12px] font-semibold text-[#558b2f]">PDF</button><button className="rounded border border-[#558b2f] bg-[#f1f8e9] px-4 py-2 text-[12px] font-semibold text-[#558b2f]">Excel</button></div><BottomNav active="Reports"/></Shell>}

export function GateEntryScreen({onBack}:BackProps){return <Shell><StatusBar/><BackHeader title="Gate Entry" onBack={onBack}/><div className="flex flex-col items-center gap-6 p-8"><div className="relative size-[220px] overflow-hidden rounded-3xl bg-black"><img src="https://www.figma.com/api/mcp/asset/671ce981-8826-44be-8645-9ee26aa93c90.png" className="h-full w-full object-cover"/><div className="absolute left-2 top-2 h-7 w-0.5 bg-[#558b2f]"/><div className="absolute left-2 top-2 h-0.5 w-7 bg-[#558b2f]"/><div className="absolute right-2 top-2 h-7 w-0.5 bg-[#558b2f]"/><div className="absolute right-2 top-2 h-0.5 w-7 bg-[#558b2f]"/><div className="absolute left-2 right-2 top-1/2 h-0.5 bg-[#558b2f]/60"/></div><div className="text-[14px] text-[#64748b]">Align QR code within frame</div><div className="font-semibold text-[#558b2f] underline">Manual Entry</div></div><Card className="m-4 border border-dashed border-[#558b2f] bg-[#f1f8e9] p-4"><div className="flex items-start justify-between"><div><div className="text-[14px] font-semibold">AP28AB1234 • Chilli</div><div className="text-[11px] text-[#64748b]">Token ID: TRD-CHL-089234</div></div><span className="rounded bg-[#f1f8e9] px-2 py-1 text-[11px] font-semibold uppercase text-[#558b2f]">Verified</span></div><div className="my-4 border-t border-dashed border-[#cbd5e1]"/><div className="grid grid-cols-3 gap-3 text-[12px]"><div><div className="text-[#64748b]">Driver</div><div className="font-semibold">Mahesh</div></div><div><div className="text-[#64748b]">Weight</div><div className="font-semibold">2500 kg</div></div><div><div className="text-[#64748b]">Bags</div><div className="font-semibold">50</div></div></div></Card><div className="px-4"><button className="w-full rounded-lg bg-[#558b2f] py-3 text-[14px] font-semibold text-white">Admit Vehicle</button></div><BottomNav active="Entry"/></Shell>}

export function ManualEntryScreen({onBack}:BackProps){const fields=[['Vehicle Number','AP 28 AB 1234'],['Driver Name','Mahesh Kumar'],['Commodity','Chilli (Dry)'],['No. of Bags','50'],['Producer Name','Rajesh Kumar'],['CA Name','Priya Agencies']];return <Shell><StatusBar/><div className="bg-[#ffb300] p-2 text-center text-[11px] font-bold text-white">OFFLINE MODE: Sync will resume when connected</div><BackHeader title="Manual Entry" onBack={onBack}/><div className="space-y-5 p-4">{fields.map(([l,v])=><div key={l}><div className="mb-2 text-[12px] font-medium text-[#64748b]">{l}</div><div className="flex h-11 items-center justify-between rounded-lg border bg-white px-3 text-[14px]">{v}<span className="text-[#64748b]">{l==='Commodity'?'⌄':''}</span></div></div>)}<button className="w-full rounded-lg bg-[#558b2f] py-3 text-[14px] font-semibold text-white">Submit &amp; Generate Temp QR</button></div><BottomNav active="Entry"/></Shell>}

export function QueueManagementScreen({onBack}:BackProps){const q=[['AP28AB1234','Chilli • 45m wait','High'],['TS09CD4567','Cotton • 20m wait','Normal'],['AP07XY9988','Chilli • 15m wait','Normal']];return <Shell><StatusBar/><div className="flex items-center justify-between p-4"><h1 className="text-[20px] font-bold">Queue Management</h1><div className="text-[14px] font-semibold text-[#64748b]">3/5 Bays •</div></div><div className="flex gap-5 bg-white px-4"><div className="border-b-2 border-[#558b2f] py-3 text-[14px] font-semibold text-[#558b2f]">All Queue</div><div className="py-3 text-[14px] text-[#64748b]">By Commodity</div><div className="py-3 text-[14px] text-[#64748b]">By Priority</div></div><div className="space-y-3 p-4">{q.map(([vehicle,meta,priority])=><Card key={vehicle} className={`flex items-center gap-3 border p-3 ${priority==='High'?'border-[#ff8f00]':'border-white'}`}><div className="text-xl text-[#64748b]">⋮⋮</div><div className="min-w-0 flex-1"><div className="font-semibold">{vehicle}</div><div className="text-[11px] text-[#64748b]">{meta}</div></div><div className="flex flex-col items-end gap-2"><span className={`rounded px-2 py-1 text-[11px] font-semibold uppercase ${priority==='High'?'bg-[#fff3e0] text-[#ff8f00]':'bg-[#f1f5f9] text-[#64748b]'}`}>{priority}</span><button className="rounded bg-[#558b2f] px-3 py-2 text-[11px] font-bold text-white">Assign Bay</button></div></Card>)}<h2 className="pt-2 text-[18px] font-semibold">Bay Map</h2><div className="grid grid-cols-5 gap-2">{[['B1','#558b2f','occupied'],['B2','#558b2f','occupied'],['B3','#ffb300','reserved'],['B4','#10b981','available'],['B5','#10b981','available']].map(([b,c,s])=><div key={b} className="rounded-lg py-3 text-center text-white" style={{background:c as string}}><div className="font-semibold">{b}</div><div className="text-[11px] opacity-80">{s}</div></div>)}</div></div><BottomNav active="Auctions"/></Shell>}

export function AuctionBoardScreen({onBack}:BackProps){const lots=['AG-556','AG-557'];return <Shell><StatusBar/><BackHeader title="Auction Board" onBack={onBack}/><div className="flex gap-5 bg-white px-4"><div className="border-b-2 border-[#ff8f00] py-3 text-[14px] font-semibold text-[#ff8f00]">Live (3)</div><div className="py-3 text-[14px] text-[#64748b]">Upcoming (2)</div><div className="py-3 text-[14px] text-[#64748b]">Completed (5)</div></div><div className="space-y-4 p-4">{lots.map(l=><Card key={l} className="border-t-4 border-[#ff8f00] p-4 shadow-sm"><div className="flex items-start justify-between"><div><div className="font-semibold">● LOT #{l}</div><div className="text-[11px] text-[#64748b]">Chilli Grade A • 120 MT</div></div><div className="text-right"><div className="text-[11px] font-bold text-[#ff8f00]">TIME LEFT</div><div className="font-semibold text-[#ff8f00]">◷ 02:15</div></div></div><div className="mt-4 flex items-end justify-between"><div><div className="text-[11px] text-[#64748b]">CURRENT BID</div><div className="text-2xl font-extrabold text-[#ff8f00]">₹158/kg</div></div><div className="text-center"><div className="text-[11px] text-[#64748b]">RANK</div><div className="text-[18px] font-semibold text-[#10b981]">A</div></div><button className="rounded-lg bg-[#558b2f] px-5 py-2 text-[14px] font-semibold text-white">View</button></div><div className="my-3 border-t border-[#e2e8f0]"/><div className="flex gap-4 text-[11px] text-[#64748b]"><span>12 Participants</span><span>Last bid 10s ago</span></div></Card>)}</div><div className="mt-auto border-t bg-white p-4"><div className="mb-2 text-[12px] font-medium text-[#64748b]">AUTHORIZED STAFF ACTIONS</div><div className="grid grid-cols-3 gap-2"><button className="rounded-lg bg-[#558b2f] py-3 text-white">Start</button><button className="rounded-lg bg-[#ef4444] py-3 text-white">Force Close</button><button className="rounded-lg bg-[#ff8f00] py-3 text-white">Extend</button></div></div><BottomNav active="Auctions"/></Shell>}

export function WeighbridgeScreen({onBack}:BackProps){return <Shell><StatusBar/><BackHeader title="Weighbridge" onBack={onBack}/><div className="space-y-5 p-4"><div><div className="mb-2 text-[12px] font-medium text-[#64748b]">Select Lot</div><div className="flex h-11 items-center justify-between rounded-lg border-2 border-[#558b2f] bg-white px-3 text-[14px] font-semibold">LOT-556 Chilli <span>⌄</span></div></div><div className="grid grid-cols-2 gap-3"><Card className="border border-[#558b2f] p-4"><div className="text-[12px] text-[#64748b]">Gross Weight</div><div className="mt-2 text-xl font-bold">12,500 kg</div><div className="text-[11px] text-[#64748b]">WB-01</div><button className="mt-4 w-full rounded-lg bg-[#558b2f] py-3 text-[14px] font-semibold text-white">Capture</button></Card><Card className="border border-[#2196f3] p-4"><div className="text-[12px] text-[#64748b]">Tare Weight</div><div className="mt-2 text-xl font-bold">2,500 kg</div><div className="text-[11px] text-[#64748b]">WB-01</div><button className="mt-4 w-full rounded-lg bg-[#2196f3] py-3 text-[14px] font-semibold text-white">Capture</button></Card></div><Card className="p-5 text-center"><div className="text-[12px] font-medium text-[#64748b]">NET WEIGHT</div><div className="text-4xl font-extrabold text-[#558b2f]">10,000 kg</div><span className="rounded bg-[#f1f8e9] px-2 py-1 text-[11px] font-semibold text-[#558b2f]">VERIFIED</span></Card><div><h2 className="mb-3 text-[18px] font-semibold">Unloading Confirmation</h2><div className="flex justify-between text-[14px]"><span className="text-[#64748b]">Bag Count</span><span className="font-semibold">50 Bags</span></div><div className="mt-3 flex gap-2"><div className="size-16 rounded bg-[#dfe7ef]"/><div className="size-16 rounded bg-[#d2dce7]"/><div className="size-16 rounded bg-[#c9d8d3]"/><div className="grid size-16 place-items-center rounded bg-[#cbd5e1] text-xl">⌂</div></div></div><button className="w-full rounded-lg bg-[#558b2f] py-3 text-[14px] font-semibold text-white">↻ Save &amp; Sync</button><div className="text-center text-[11px] text-[#10b981]">Synced to CA and Buyer successfully</div></div><BottomNav active="Weigh"/></Shell>}

export function YardReportsScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function ComplianceOverviewScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function NationalMarketScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function AndhraOverviewScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function DisputeOversightScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function PriceBulletinScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function MarketYardScreen({onBack}:BackProps){return <StateOverviewScreen onBack={onBack}/>}
export function GateEntryManualScreen({onBack}:BackProps){return <ManualEntryScreen onBack={onBack}/>}
export function YardDashboardPlaceholderScreen({onBack}:BackProps){return <YardDashboardScreen onBack={onBack}/>}
